#!/usr/bin/env zsh

# Install native apps
run_apps() {
	#utils
	brew cask install alfred
	brew cask install cakebrew
	brew cask install calibre
	brew cask install firefox
	brew cask install gifox
	brew cask install google-chrome
	brew cask install gpg-suite-no-mail
	brew cask install istat-menus
	brew cask install keka
	brew cask install little-snitch
	brew cask install macupdater
	brew cask install miro
	brew cask install muzzle
	brew cask install notion
	brew cask install numi
	brew cask install rocket
	brew cask install skype
	brew cask install spotify
	brew cask install suspicious-package
	brew cask install ultimaker-cura
	brew cask install vlc
	brew cask install whatsapp
	brew cask install zeplin

	# dev
	brew cask install cyberduck
	brew cask install docker
	brew cask install github
	brew cask install gitkraken
	brew cask install graphql-playground
	brew cask install insomnia
	brew cask install iterm2
	brew cask install imageoptim
	brew cask install jetbrains-toolbox
	brew cask install kitematic
	brew cask install majestic
	brew cask install vercel
	brew cask install postman
	brew cask install virtualbox
	brew cask install visual-studio-code-insiders

	# colorpickers
	brew cask install colorpicker-materialdesign colorpicker-propicker colorpicker-skalacolor
}
