#!/usr/bin/env zsh

# Install native apps
run_apps() {
	#utils
	brew cask install calibre
	brew cask install firefox
	brew cask install google-chrome
	brew cask install keka
	brew cask install macupdater
	brew cask install muzzle
	brew cask install notion
	brew cask install slack
	brew cask install spotify
	brew cask install suspicious-package
	brew cask install ultimaker-cura
	brew cask install vlc
	brew cask install whatsapp
	brew cask install zeplin

	# dev
	brew cask install cyberduck
	brew cask install docker
	brew cask install github
	brew cask install gitkraken
	brew cask install graphql-playground
	brew cask install imageoptim
	brew cask install insomnia
	brew cask install iterm2
	brew cask install jetbrains-toolbox
	brew cask install kitematic
	brew cask install mockoon
	brew cask install now
	brew cask install postman
	brew cask install virtualbox

	# colorpickers
	brew cask install colorpicker-materialdesign colorpicker-propicker colorpicker-skalacolor
}
