#!/usr/bin/env zsh

dotfiles=(.ackrc .aliases .config .editorconfig .exports .functions .gitattributes .gitconfig .gitignore .npmrc .osx .vim .vimrc .zshrc )

# Install dotfiles
run_dotfiles() {
	for i in "${dotfiles[@]}"; do
		if [[ "$i" == ".gitconfig" && -f ~/.gitconfig && "$USER" != "wylkon" ]]; then
			e_warning ".gitconfig already exists, do it manually"
		elif [[ "$i" == ".npmrc" && -f ~/.npmrc && "$USER" != "wylkon" ]]; then
			e_warning ".npmrc already exists, do it manually"
		else
			rm -rf ~/"$i"
			ln -s .dotfiles/"$i" ~
		fi
	done

	source ~/.zshrc
}
