#!/usr/bin/env bash

run_rubygems() {
    e_process "Init Rbenv"
    echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.zshrc
    rbenv init

    e_process "Installing the latest version of Ruby"
    rbenv install 2.7.1
    rbenv global 2.7.1
    
    e_process "Installing the latest version of Ruby"
    gem install bundler

    e_process "Configuring Bundler for faster, parallel gem installation ..."
    number_of_cores=$(sysctl -n hw.ncpu)
    bundle config --global jobs $((number_of_cores - 1))

    e_process "Installing utils..."
		gem install colorls
		gem install travis
		gem install wordmove

    [[ $? ]] && e_success "Done"
}
