#!/usr/bin/env zsh

run_tools() {
	if ! type_exists 'push'; then
		e_process "Installing git-friendly"
		sudo curl -sS https://raw.githubusercontent.com/jamiew/git-friendly/master/install.sh | bash
	fi

	if ! type_exists 'pygmentize'; then
		e_process "Installing pygments"
		sudo easy_install Pygments
	fi

	e_process "Installing chmodr"
	sudo cp -p ./bin/chmodr.sh /usr/local/bin/chmodr

	e_process "Installing colors"
	sudo cp -p ./bin/colors.sh /usr/local/bin/colors

	e_process "Installing docker-start"
	sudo cp -p ./bin/docker-start.sh /usr/local/bin/docker-start

	e_process "Installing search"
	sudo cp -p ./bin/search.sh /usr/local/bin/search

	e_process "Installing service"
	sudo cp -p ./bin/service.sh /usr/local/bin/service

	e_process "Define ZSH as default"
	chsh -s /bin/zsh
	
	e_process "Installing Oh-my-zsh"
	if [ ! -e ~/.oh-my-zsh ]; then
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  fi

	[[ $? ]] && e_success "Done"
}
